import { z } from "zod";

export const Alliance = ["Red", "Blue"] as const;
export const MatchLevel = [
  "None",
  "Practice",
  "Qualification",
  "Playoff",
] as const;

export const CommonEntrySchema = z.object({
  eventKey: z.string(),
  matchLevel: z.union([
    z.literal("None"),
    z.literal("Practice"),
    z.literal("Qualification"),
    z.literal("Playoff"),
  ]),
  matchNumber: z.number().int().nonnegative(),
  teamNumber: z.number().int().nonnegative(),
  alliance: z.union([z.literal("Red"), z.literal("Blue")]),
  robotNumber: z.union([
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
  ]),
  deviceTeamNumber: z.number().int().nonnegative(),
  deviceId: z.string(),
  scoutTeamNumber: z.number().int().nonnegative(),
  scoutName: z.string(),
  flag: z.string(),
  finalTimeStamp: z.string(),
});
export type CommonEntry = z.infer<typeof CommonEntrySchema>;
export type CommonEntryColumn = keyof CommonEntry;
export const CommonEntryColumns: CommonEntryColumn[] = [
  "eventKey",
  "matchLevel",
  "matchNumber",
  "teamNumber",
  "alliance",
  "robotNumber",
  "deviceTeamNumber",
  "deviceId",
  "scoutTeamNumber",
  "scoutName",
  "flag",
  "finalTimeStamp"
] as CommonEntryColumn[];

export const TeamMatchEntrySchema = CommonEntrySchema.omit({
  robotNumber: true,
}).extend({
  robotNumber: z.union([z.literal(1), z.literal(2), z.literal(3)]),
  noShow: z.boolean(),
  comments: z.string().nullable(),
  startZone: z.union([
    z.literal("depot"),
    z.literal("mid"),
    z.literal("outpost"),
  ]).nullable(),
  autoFuelScoredFromHub: z.boolean().nullable(),
  autoFuelScoredFromTower: z.boolean().nullable(),
  autoFuelScoredFromDepot: z.boolean().nullable(),
  autoFuelScoredFromOutpost: z.boolean().nullable(),
  autoFuelScoredFromTrenchOutpost: z.boolean().nullable(),
  autoFuelScoredFromTrenchDepot: z.boolean().nullable(),
  autoFuelScoredFromBumpOutpost: z.boolean().nullable(),
  autoFuelScoredFromBumpDepot: z.boolean().nullable(),
  autoFuelScoredFromOther: z.boolean().nullable(),
  autoFuelPassed: z.boolean().nullable(),
  autoClimbPosition: z.union([
    z.literal("outpost"),
    z.literal("center"),
    z.literal("depot"),
    z.literal("other"),
  ]).nullable(),
  autoClimbAttempted: z.boolean().nullable(),
  autoClimbLevel: z.union([
    z.literal(1),
    z.literal(2),
    z.literal(3),
  ]).nullable(),
  autoFuelScored: z.number().int().nonnegative().nullable(),
  autoFuelScoredPercentage: z.number().int().min(0).max(100).nullable(),


  teleFuelScored: z.number().int().nonnegative().nullable(),
  teleFuelScoredPercentage: z.number().int().min(0).max(100).nullable(),
  totalAllianceFuelScoredScout: z.number().int().nonnegative().nullable(),
  totalAllianceFuelScoredOfficial: z.number().int().nonnegative().nullable(),
  teleCycles: z.number().int().nonnegative().nullable(),
  teleFuelScoredFromHub: z.boolean().nullable(),
  teleFuelScoredFromTower: z.boolean().nullable(),
  teleFuelScoredFromDepot: z.boolean().nullable(),
  teleFuelScoredFromOutpost: z.boolean().nullable(),
  teleFuelScoredFromTrenchOutpost: z.boolean().nullable(),
  teleFuelScoredFromTrenchDepot: z.boolean().nullable(),
  teleFuelScoredFromBumpOutpost: z.boolean().nullable(),
  teleFuelScoredFromBumpDepot: z.boolean().nullable(),
  teleFuelScoredFromOther: z.boolean().nullable(),
  teleFuelPassed: z.boolean().nullable(),

  teleInactiveDefenseRoleEffectiveness: z.number().int().min(0).max(10).nullable(),
  teleInactiveIntakingRoleEffectiveness: z.number().int().min(0).max(10).nullable(),
  teleInactiveFeedingRoleEffectiveness: z.number().int().min(0).max(10).nullable(),
  teleInactiveFuelPassed: z.number().int().nonnegative().nullable(),



  endClimbAttempted: z.boolean().nullable(),
  endClimbPosition: z.union([
    z.literal("outpost"),
    z.literal("center"),
    z.literal("depot"),
    z.literal("other"),
  ]).nullable(),
  autoRobotGotStuck: z.boolean().nullable(),
  autoRobotStuckTrench: z.boolean().nullable(),
  autoRobotStuckBump: z.boolean().nullable(),
  autoRobotStuckFuel: z.boolean().nullable(),
  autoRobotTipped: z.boolean().nullable(),
  autoRobotTraverseTrench: z.boolean().nullable(),
  autoRobotTraverseBump: z.boolean().nullable(),
  teleRobotGotStuck: z.boolean().nullable(),
  teleRobotStuckTrench: z.boolean().nullable(),
  teleRobotStuckBump: z.boolean().nullable(),
  teleRobotStuckFuel: z.boolean().nullable(),
  teleRobotTipped: z.boolean().nullable(),
  teleRobotTraverseTrench: z.boolean().nullable(),
  teleRobotTraverseBump: z.boolean().nullable(),
  died: z.boolean().nullable(),
  dataConfidence: z.number().int().min(0).max(10).nullable(),
  fuelPercentagesDiscussed: z.boolean().nullable(),
  fuelQualitative: z.number().int().min(0).max(10).nullable(),
});
export type TeamMatchEntry = z.infer<typeof TeamMatchEntrySchema>;
export type TeamMatchEntryColumn = keyof TeamMatchEntry;
export const TeamMatchEntryColumns: TeamMatchEntryColumn[] = [
  ...CommonEntryColumns,

  "noShow",
  "comments",
  "startZone",
  "autoFuelScoredFromHub",
  "autoFuelScoredFromTower",
  "autoFuelScoredFromDepot",
  "autoFuelScoredFromOutpost",
  "autoFuelScoredFromTrenchOutpost",
  "autoFuelScoredFromTrenchDepot",
  "autoFuelScoredFromBumpOutpost",
  "autoFuelScoredFromBumpDepot",
  "autoFuelScoredFromOther",
  "autoFuelPassed",
  "autoClimbPosition",
  "autoClimbAttempted",
  "autoClimbLevel",
  "autoFuelScored",
  "autoFuelScoredPercentage",
  "teleFuelScored",
  "teleFuelScoredPercentage",
  "totalAllianceFuelScoredScout",
  "totalAllianceFuelScoredOfficial",
  "teleCycles",
  "teleFuelScoredFromHub",
  "teleFuelScoredFromTower",
  "teleFuelScoredFromDepot",
  "teleFuelScoredFromOutpost",
  "teleFuelScoredFromTrenchOutpost",
  "teleFuelScoredFromTrenchDepot",
  "teleFuelScoredFromBumpOutpost",
  "teleFuelScoredFromBumpDepot",
  "teleFuelScoredFromOther",
  "teleFuelPassed",

  "teleInactiveDefenseRoleEffectiveness",
  "teleInactiveIntakingRoleEffectiveness",
  "teleInactiveFeedingRoleEffectiveness",
  "teleInactiveFuelPassed",

  "endClimbAttempted",
  "endClimbPosition",
  "autoRobotGotStuck",
  "autoRobotStuckTrench",
  "autoRobotStuckBump",
  "autoRobotStuckFuel",
  "autoRobotTipped",
  "autoRobotTraverseTrench",
  "autoRobotTraverseBump",
  "teleRobotGotStuck",
  "teleRobotStuckTrench",
  "teleRobotStuckBump",
  "teleRobotStuckFuel",
  "teleRobotTipped",
  "teleRobotTraverseTrench",
  "teleRobotTraverseBump",
  "died",
  "dataConfidence",
  "fuelPercentagesDiscussed",
  "fuelQualitative"
] as TeamMatchEntryColumn[];
export const TeamMatchEntryInit: TeamMatchEntry = {
  eventKey: "",
  matchLevel: "Qualification",
  matchNumber: 1,
  teamNumber: 0,
  alliance: "Red",
  robotNumber: 1,
  deviceTeamNumber: 0,
  deviceId: "",
  scoutTeamNumber: NaN,
  scoutName: "",
  flag: "",
  finalTimeStamp: "",

  noShow: false,
  comments: null,
  startZone: null,
  autoFuelScoredFromHub: null,
  autoFuelScoredFromTower: null,
  autoFuelScoredFromDepot: null,
  autoFuelScoredFromOutpost: null,
  autoFuelScoredFromTrenchOutpost: null,
  autoFuelScoredFromTrenchDepot: null,
  autoFuelScoredFromBumpOutpost: null,
  autoFuelScoredFromBumpDepot: null,
  autoFuelScoredFromOther: null,
  autoFuelPassed: null,
  autoClimbPosition: null,
  autoClimbAttempted: null,
  autoClimbLevel: null,
  autoFuelScored: null,
  autoFuelScoredPercentage: null,
  teleFuelScored: null,
  teleFuelScoredPercentage: null,
  totalAllianceFuelScoredScout: null,
  totalAllianceFuelScoredOfficial: null,
  teleCycles: null,
  teleFuelScoredFromHub: null,
  teleFuelScoredFromTower: null,
  teleFuelScoredFromDepot: null,
  teleFuelScoredFromOutpost: null,
  teleFuelScoredFromTrenchOutpost: null,
  teleFuelScoredFromTrenchDepot: null,
  teleFuelScoredFromBumpOutpost: null,
  teleFuelScoredFromBumpDepot: null,
  teleFuelScoredFromOther: null,
  teleFuelPassed: null,

  teleInactiveDefenseRoleEffectiveness: null,
  teleInactiveIntakingRoleEffectiveness: null,
  teleInactiveFeedingRoleEffectiveness: null,
  teleInactiveFuelPassed: null,

  endClimbAttempted: null,
  endClimbPosition: null,
  autoRobotGotStuck: null,
  autoRobotStuckTrench: null,
  autoRobotStuckBump: null,
  autoRobotStuckFuel: null,
  autoRobotTipped: null,
  autoRobotTraverseTrench: null,
  autoRobotTraverseBump: null,
  teleRobotGotStuck: null,
  teleRobotStuckTrench: null,
  teleRobotStuckBump: null,
  teleRobotStuckFuel: null,
  teleRobotTipped: null,
  teleRobotTraverseTrench: null,
  teleRobotTraverseBump: null,
  died: null,
  dataConfidence: null,
  fuelPercentagesDiscussed: null,
  fuelQualitative: null,
};
export const TeamMatchEntryNoShowInit: TeamMatchEntry = {
  eventKey: "",
  matchLevel: "Qualification",
  matchNumber: 1,
  teamNumber: 0,
  alliance: "Red",
  robotNumber: 1,
  deviceTeamNumber: 0,
  deviceId: "",
  scoutTeamNumber: NaN,
  scoutName: "",
  flag: "",
  finalTimeStamp: "",

  noShow: true,
  comments: null,
  startZone: null,
  autoFuelScoredFromHub: null,
  autoFuelScoredFromTower: null,
  autoFuelScoredFromDepot: null,
  autoFuelScoredFromOutpost: null,
  autoFuelScoredFromTrenchOutpost: null,
  autoFuelScoredFromTrenchDepot: null,
  autoFuelScoredFromBumpOutpost: null,
  autoFuelScoredFromBumpDepot: null,
  autoFuelScoredFromOther: null,
  autoFuelPassed: null,
  autoClimbPosition: null,
  autoClimbAttempted: null,
  autoClimbLevel: null,
  autoFuelScored: null,
  autoFuelScoredPercentage: null,
  teleFuelScored: null,
  teleFuelScoredPercentage: null,
  totalAllianceFuelScoredScout: null,
  totalAllianceFuelScoredOfficial: null,
  teleCycles: null,
  teleFuelScoredFromHub: null,
  teleFuelScoredFromTower: null,
  teleFuelScoredFromDepot: null,
  teleFuelScoredFromOutpost: null,
  teleFuelScoredFromTrenchOutpost: null,
  teleFuelScoredFromTrenchDepot: null,
  teleFuelScoredFromBumpOutpost: null,
  teleFuelScoredFromBumpDepot: null,
  teleFuelScoredFromOther: null,
  teleFuelPassed: null,

  teleInactiveDefenseRoleEffectiveness: null,
  teleInactiveIntakingRoleEffectiveness: null,
  teleInactiveFeedingRoleEffectiveness: null,
  teleInactiveFuelPassed: null,

  endClimbAttempted: null,
  endClimbPosition: null,
  autoRobotGotStuck: null,
  autoRobotStuckTrench: null,
  autoRobotStuckBump: null,
  autoRobotStuckFuel: null,
  autoRobotTipped: null,
  autoRobotTraverseTrench: null,
  autoRobotTraverseBump: null,
  teleRobotGotStuck: null,
  teleRobotStuckTrench: null,
  teleRobotStuckBump: null,
  teleRobotStuckFuel: null,
  teleRobotTipped: null,
  teleRobotTraverseTrench: null,
  teleRobotTraverseBump: null,
  died: null,
  dataConfidence: null,
  fuelPercentagesDiscussed: null,
  fuelQualitative: null,
};



export const UserPermLevel = [
  "none",
  "demo",
  "team",
  "datamanage",
  "admin",
] as const;
export const UserSchema = z.object({
  username: z.string(),
  permLevel: z.union([
    z.literal("none"),
    z.literal("demo"),
    z.literal("team"),
    z.literal("datamanage"),
    z.literal("admin"),
  ]),
  teamNumber: z.number().int().nonnegative(),
  hashedPassword: z.string(),
  discordRoleId: z.string().nullable().optional(),
});
export type User = z.infer<typeof UserSchema>;
export type UserColumn = keyof User;
export const UserColumns: UserColumn[] = [
  "username",
  "permLevel",
  "teamNumber",
  "hashedPassword",
  "discordRoleId",
];

export const PitScoutEntrySchema = z.object({
  eventKey: z.string(),
  teamNumber: z.number().int().nonnegative(),
  deviceTeamNumber: z.number().int().nonnegative(),
  deviceId: z.string(),
  scoutTeamNumber: z.number().int().nonnegative(),
  scoutName: z.string(),
  uploadedAt: z.string(),

  startingLocation: z.union([
    z.literal("trenchDepot"),
    z.literal("bumpDepot"),
    z.literal("hub"),
    z.literal("bumpOutpost"),
    z.literal("trenchOutpost"),
  ]).nullable(),

  pitAutoShootHub: z.boolean().nullable(),
  pitAutoShootTower: z.boolean().nullable(),
  pitAutoShootDepot: z.boolean().nullable(),
  pitAutoShootOutpost: z.boolean().nullable(),
  pitAutoShootTrenchOutpost: z.boolean().nullable(),
  pitAutoShootTrenchDepot: z.boolean().nullable(),
  pitAutoShootBumpOutpost: z.boolean().nullable(),
  pitAutoShootBumpDepot: z.boolean().nullable(),
  pitAutoShootOther: z.boolean().nullable(),

  pitPickupFloor: z.boolean().nullable(),
  pitPickupOutpost: z.boolean().nullable(),
  pitPickupDepot: z.boolean().nullable(),
  pitPickupNo: z.boolean().nullable(),

  pitFeedZone1: z.boolean().nullable(),
  pitFeedZone2: z.boolean().nullable(),
  pitFeedOutpost: z.boolean().nullable(),

  pitTraverseTrench: z.boolean().nullable(),
  pitTraverseBump: z.boolean().nullable(),

  pitAutoMove: z.boolean().nullable(),
  pitAutoScore: z.boolean().nullable(),
  pitAutoClimb: z.boolean().nullable(),
  pitAutoPickup: z.boolean().nullable(),
  pitNumberOfAutos: z.number().int().nonnegative().nullable(),

  pitHopperSize: z.number().int().nonnegative().nullable(),

  pitClimbLocation: z.union([
    z.literal("depot"),
    z.literal("center"),
    z.literal("outpost"),
    z.literal("other"),
  ]).nullable(),
  pitClimbLevel: z.union([
    z.literal(1),
    z.literal(2),
    z.literal(3),
  ]).nullable(),
  pitClimbTime: z.number().nonnegative().nullable(),

  pitShooterBps: z.number().nonnegative().nullable(),

  pitHumanScore: z.boolean().nullable(),
  pitHumanFeed: z.boolean().nullable(),
  pitHumanOther: z.boolean().nullable(),

  pitTelePrimary: z.union([
    z.literal("score"),
    z.literal("feed"),
    z.literal("climb"),
    z.literal("defense"),
    z.literal("pickupHerd"),
  ]).nullable(),
  pitTeleScore: z.boolean().nullable(),
  pitTeleFeed: z.boolean().nullable(),
  pitTeleClimb: z.boolean().nullable(),
  pitTeleDefense: z.boolean().nullable(),
  pitTelePickupHerd: z.boolean().nullable(),

  pitTeleShootHub: z.boolean().nullable(),
  pitTeleShootTower: z.boolean().nullable(),
  pitTeleShootDepot: z.boolean().nullable(),
  pitTeleShootOutpost: z.boolean().nullable(),
  pitTeleShootTrenchOutpost: z.boolean().nullable(),
  pitTeleShootTrenchDepot: z.boolean().nullable(),
  pitTeleShootBumpOutpost: z.boolean().nullable(),
  pitTeleShootBumpDepot: z.boolean().nullable(),
  pitTeleShootOther: z.boolean().nullable(),
  pitTeleShootAny: z.boolean().nullable(),
});
export type PitScoutEntry = z.infer<typeof PitScoutEntrySchema>;
export type PitScoutEntryColumn = keyof PitScoutEntry;
export const PitScoutEntryColumns: PitScoutEntryColumn[] = [
  "eventKey",
  "teamNumber",
  "deviceTeamNumber",
  "deviceId",
  "scoutTeamNumber",
  "scoutName",
  "uploadedAt",
  "startingLocation",
  "pitAutoShootHub",
  "pitAutoShootTower",
  "pitAutoShootDepot",
  "pitAutoShootOutpost",
  "pitAutoShootTrenchOutpost",
  "pitAutoShootTrenchDepot",
  "pitAutoShootBumpOutpost",
  "pitAutoShootBumpDepot",
  "pitAutoShootOther",
  "pitPickupFloor",
  "pitPickupOutpost",
  "pitPickupDepot",
  "pitPickupNo",
  "pitFeedZone1",
  "pitFeedZone2",
  "pitFeedOutpost",
  "pitTraverseTrench",
  "pitTraverseBump",
  "pitAutoMove",
  "pitAutoScore",
  "pitAutoClimb",
  "pitAutoPickup",
  "pitNumberOfAutos",
  "pitHopperSize",
  "pitClimbLocation",
  "pitClimbLevel",
  "pitClimbTime",
  "pitShooterBps",
  "pitHumanScore",
  "pitHumanFeed",
  "pitHumanOther",
  "pitTelePrimary",
  "pitTeleScore",
  "pitTeleFeed",
  "pitTeleClimb",
  "pitTeleDefense",
  "pitTelePickupHerd",
  "pitTeleShootHub",
  "pitTeleShootTower",
  "pitTeleShootDepot",
  "pitTeleShootOutpost",
  "pitTeleShootTrenchOutpost",
  "pitTeleShootTrenchDepot",
  "pitTeleShootBumpOutpost",
  "pitTeleShootBumpDepot",
  "pitTeleShootOther",
  "pitTeleShootAny",
] as PitScoutEntryColumn[];

export const PitScoutEntryInit: PitScoutEntry = {
  eventKey: "",
  teamNumber: 0,
  deviceTeamNumber: 0,
  deviceId: "",
  scoutTeamNumber: NaN,
  scoutName: "",
  uploadedAt: "",

  startingLocation: null,

  pitAutoShootHub: null,
  pitAutoShootTower: null,
  pitAutoShootDepot: null,
  pitAutoShootOutpost: null,
  pitAutoShootTrenchOutpost: null,
  pitAutoShootTrenchDepot: null,
  pitAutoShootBumpOutpost: null,
  pitAutoShootBumpDepot: null,
  pitAutoShootOther: null,

  pitPickupFloor: null,
  pitPickupOutpost: null,
  pitPickupDepot: null,
  pitPickupNo: null,

  pitFeedZone1: null,
  pitFeedZone2: null,
  pitFeedOutpost: null,

  pitTraverseTrench: null,
  pitTraverseBump: null,

  pitAutoMove: null,
  pitAutoScore: null,
  pitAutoClimb: null,
  pitAutoPickup: null,
  pitNumberOfAutos: null,

  pitHopperSize: null,

  pitClimbLocation: null,
  pitClimbLevel: null,
  pitClimbTime: null,

  pitShooterBps: null,

  pitHumanScore: null,
  pitHumanFeed: null,
  pitHumanOther: null,

  pitTelePrimary: null,
  pitTeleScore: null,
  pitTeleFeed: null,
  pitTeleClimb: null,
  pitTeleDefense: null,
  pitTelePickupHerd: null,

  pitTeleShootHub: null,
  pitTeleShootTower: null,
  pitTeleShootDepot: null,
  pitTeleShootOutpost: null,
  pitTeleShootTrenchOutpost: null,
  pitTeleShootTrenchDepot: null,
  pitTeleShootBumpOutpost: null,
  pitTeleShootBumpDepot: null,
  pitTeleShootOther: null,
  pitTeleShootAny: null,
};

export const DBEventSchema = z.object({
  eventKey: z.string(),
  eventName: z.string(),
});
export type DBEvent = z.infer<typeof DBEventSchema>;
export type DBEventColumn = keyof DBEvent;
export const DBEventColumns: DBEventColumn[] = ["eventKey", "eventName"];

export const MatchSchema = z.object({
  eventKey: z.string(),
  matchLevel: z.union([
    z.literal("None"),
    z.literal("Practice"),
    z.literal("Qualification"),
    z.literal("Playoff"),
  ]),
  matchNumber: z.number().int().nonnegative(),
  red1: z.number().int().nonnegative(),
  red2: z.number().int().nonnegative(),
  red3: z.number().int().nonnegative(),
  blue1: z.number().int().nonnegative(),
  blue2: z.number().int().nonnegative(),
  blue3: z.number().int().nonnegative(),
});
export type Match = z.infer<typeof MatchSchema>;
export type MatchColumn = keyof Match;
export const MatchColumns: MatchColumn[] = [
  "eventKey",
  "matchLevel",
  "matchNumber",
  "red1",
  "red2",
  "red3",
  "blue1",
  "blue2",
  "blue3",
];
